### ISSUE TITLE
Decorum class runs wrapped function via a `call()` method

### ISSUE THREAD

**Issue by benoitbryon** [zeekay/decorum#23]
At the moment, `decorum.Decorum` offers two entry points to customize decorators:

* `init()` setups the decorator instance;
* `wraps()` actually decorates the function.

What about adding a third one to run the wrapped function? It would be useful to customize things such as:

* alter input arguments
* post-process result

Overriding `__call__()` would be a bit tricky, because it does some magic, just like `__init__()`. That's why a new method would be appreciated.

**Comment by benoitbryon** [comment]
About the name: `run()` or `call()`?
`call()` would mimic `__init__()` => `init()`.
Whereas `run()` may avoid some confusions with `__call__()`.

**Comment by zeekay** [comment]
Makes sense, I like `call()`.
